apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: projectkube-club-ca
  namespace: cert-manager
spec:
  dnsNames:
  - projectkube.club 
  isCA: true
  duration: 43800h # 5 years
  commonName: projectkube.club 
  secretName: projectkube-club-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
