apiVersion: v1
data:
  config.yaml: |
    additional_display_details:
    - annotation: kiali.io/api-spec
      icon_annotation: kiali.io/api-type
      title: API Documentation
    api:
      namespaces:
        exclude:
        - ^istio-operator
        - ^kube-.*
        - ^openshift.*
        - ^ibm.*
        - ^kiali-operator
    auth:
      openid:
        additional_request_params: {}
        allowed_domains: []
        api_proxy: ''
        api_proxy_ca_data: ''
        api_token: id_token
        authentication_timeout: 300
        authorization_endpoint: ''
        client_id: ''
        disable_rbac: false
        http_proxy: ''
        https_proxy: ''
        insecure_skip_verify_tls: false
        issuer_uri: ''
        scopes:
        - openid
        - profile
        - email
        username_claim: sub
      openshift:
        client_id_prefix: kiali
      strategy: token
    custom_dashboards: []
    deployment:
      accessible_namespaces:
      - '**'
      affinity:
        node: {}
        pod: {}
        pod_anti: {}
      configmap_annotations: {}
      custom_secrets: []
      host_aliases: []
      hpa:
        api_version: autoscaling/v2beta2
        spec: {}
      image_digest: ''
      image_name: quay.io/kiali/kiali
      image_pull_policy: IfNotPresent
      image_pull_secrets: []
      image_version: v1.54.0
      ingress:
        additional_labels: {}
        class_name: nginx
        enabled: false
      instance_name: kiali
      logger:
        log_format: text
        log_level: info
        sampler_rate: '1'
        time_field_format: 2006-01-02T15:04:05Z07:00
      namespace: istio-system
      node_selector: {}
      pod_annotations: {}
      pod_labels: {}
      priority_class_name: ''
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 10m
          memory: 64Mi
      secret_name: kiali
      service_annotations: {}
      tolerations: []
      version_label: v1.54.0
      view_only_mode: false
    external_services:
      custom_dashboards:
        discovery_auto_threshold: 10
        discovery_enabled: auto
        enabled: true
        is_core: false
        namespace_label: ''
        prometheus:
          auth:
            ca_file: ''
            insecure_skip_verify: false
            password: ''
            token: ''
            type: none
            use_kiali_token: false
            username: ''
          cache_duration: 7
          cache_enabled: true
          cache_expiration: 300
          custom_headers: {}
          health_check_url: ''
          is_core: true
          query_scope: {}
          thanos_proxy:
            enabled: false
            retention_period: 7d
            scrape_interval: 30s
          url: ''
      grafana:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: 'prom-operator'
          token: ''
          type: none
          use_kiali_token: false
          username: 'admin'
        dashboards:
        - name: Istio Service Dashboard
          variables:
            namespace: var-namespace
            service: var-service
        - name: Istio Workload Dashboard
          variables:
            namespace: var-namespace
            workload: var-workload
        - name: Istio Mesh Dashboard
        - name: Istio Control Plane Dashboard
        - name: Istio Performance Dashboard
        - name: Istio Wasm Extension Dashboard
        enabled: true
        health_check_url: ''
        in_cluster_url: http://m001-grafana.monitoring:80
        is_core: false
        url: ''
      istio:
        component_status:
          components:
          - app_label: istiod
            is_core: true
            is_proxy: false
            namespace: ''
          - app_label: istio-ingressgateway
            is_core: true
            is_proxy: true
            namespace: ''
          - app_label: istio-egressgateway
            is_core: false
            is_proxy: true
            namespace: ''
          enabled: true
        config_map_name: istio
        envoy_admin_local_port: 15000
        istio_identity_domain: svc.cluster.local
        istio_injection_annotation: sidecar.istio.io/inject
        istio_sidecar_annotation: sidecar.istio.io/status
        istio_sidecar_injector_config_map_name: istio-sidecar-injector
        istiod_deployment_name: istiod
        istiod_pod_monitoring_port: 15014
        root_namespace: istio-system
        url_service_version: http://istiod.istio-system:15014/version
      prometheus:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        cache_duration: 7
        cache_enabled: true
        cache_expiration: 300
        custom_headers: {}
        health_check_url: ''
        is_core: true
        query_scope: {}
        thanos_proxy:
          enabled: false
          retention_period: 7d
          scrape_interval: 30s
        url: http://m001-kube-prometheus-stack-prometheus.monitoring:9090
      tracing:
        auth:
          ca_file: ''
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        enabled: true
        in_cluster_url: http://tracing:16685/jaeger
        is_core: false
        namespace_selector: true
        url: ''
        use_grpc: true
        whitelist_istio_system:
        - jaeger-query
        - istio-ingressgateway
    health_config:
      rate: []
    identity:
      cert_file: ''
      private_key_file: ''
    installation_tag: ''
    istio_labels:
      app_label_name: app
      injection_label_name: istio-injection
      injection_label_rev: istio.io/rev
      version_label_name: version
    istio_namespace: istio-system
    kiali_feature_flags:
      certificates_information_indicators:
        enabled: true
        secrets:
        - cacerts
        - istio-ca-secret
      clustering:
        enabled: true
      disabled_features: []
      istio_injection_action: true
      istio_upgrade_action: false
      ui_defaults:
        graph:
          find_options:
          - description: 'Find: slow edges (> 1s)'
            expression: rt > 1000
          - description: 'Find: unhealthy nodes'
            expression: '! healthy'
          - description: 'Find: unknown nodes'
            expression: name = unknown
          - description: 'Find: nodes with the 2 top rankings'
            expression: rank <= 2
          hide_options:
          - description: 'Hide: healthy nodes'
            expression: healthy
          - description: 'Hide: unknown nodes'
            expression: name = unknown
          - description: 'Hide: nodes ranked lower than the 2 top rankings'
            expression: rank > 2
          settings:
            font_label: 13
            min_font_badge: 7
            min_font_label: 10
          traffic:
            grpc: requests
            http: requests
            tcp: sent
        metrics_inbound:
          aggregations: []
        metrics_outbound:
          aggregations: []
        metrics_per_refresh: 1m
        namespaces: []
        refresh_interval: 60s
      validations:
        ignore:
        - KIA1201
    kubernetes_config:
      burst: 200
      cache_duration: 300
      cache_enabled: true
      cache_istio_types:
      - AuthorizationPolicy
      - DestinationRule
      - EnvoyFilter
      - Gateway
      - PeerAuthentication
      - RequestAuthentication
      - ServiceEntry
      - Sidecar
      - VirtualService
      - WorkloadEntry
      - WorkloadGroup
      cache_namespaces:
      - .*
      cache_token_namespace_duration: 10
      excluded_workloads:
      - CronJob
      - DeploymentConfig
      - Job
      - ReplicationController
      qps: 175
    login_token:
      expiration_seconds: 86400
      signing_key: secret:kiali-signing-key:key
    server:
      address: ''
      audit_log: true
      cors_allow_all: false
      gzip_enabled: true
      observability:
        metrics:
          enabled: true
          port: 9090
        tracing:
          collector_url: http://jaeger-collector.istio-system:14268/api/traces
          enabled: false
      port: 20001
      web_fqdn: ''
      web_history_mode: ''
      web_port: ''
      web_root: /kiali
      web_schema: ''
    version: default
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"config.yaml":"additional_display_details:\n- annotation: kiali.io/api-spec\n  icon_annotation: kiali.io/api-type\n  title: API Documentation\napi:\n  namespaces:\n    exclude:\n    - ^istio-operator\n    - ^kube-.*\n    - ^openshift.*\n    - ^ibm.*\n    - ^kiali-operator\nauth:\n  openid:\n    additional_request_params: {}\n    allowed_domains: []\n    api_proxy: ''\n    api_proxy_ca_data: ''\n    api_token: id_token\n    authentication_timeout: 300\n    authorization_endpoint: ''\n    client_id: ''\n    disable_rbac: false\n    http_proxy: ''\n    https_proxy: ''\n    insecure_skip_verify_tls: false\n    issuer_uri: ''\n    scopes:\n    - openid\n    - profile\n    - email\n    username_claim: sub\n  openshift:\n    client_id_prefix: kiali\n  strategy: token\ncustom_dashboards: []\ndeployment:\n  accessible_namespaces:\n  - '**'\n  affinity:\n    node: {}\n    pod: {}\n    pod_anti: {}\n  configmap_annotations: {}\n  custom_secrets: []\n  host_aliases: []\n  hpa:\n    api_version: autoscaling/v2beta2\n    spec: {}\n  image_digest: ''\n  image_name: quay.io/kiali/kiali\n  image_pull_policy: IfNotPresent\n  image_pull_secrets: []\n  image_version: v1.54.0\n  ingress:\n    additional_labels: {}\n    class_name: nginx\n    enabled: false\n  instance_name: kiali\n  logger:\n    log_format: text\n    log_level: info\n    sampler_rate: '1'\n    time_field_format: 2006-01-02T15:04:05Z07:00\n  namespace: istio-system\n  node_selector: {}\n  pod_annotations: {}\n  pod_labels: {}\n  priority_class_name: ''\n  replicas: 1\n  resources:\n    limits:\n      memory: 1Gi\n    requests:\n      cpu: 10m\n      memory: 64Mi\n  secret_name: kiali\n  service_annotations: {}\n  tolerations: []\n  version_label: v1.54.0\n  view_only_mode: false\nexternal_services:\n  custom_dashboards:\n    discovery_auto_threshold: 10\n    discovery_enabled: auto\n    enabled: true\n    is_core: false\n    namespace_label: ''\n    prometheus:\n      auth:\n        ca_file: ''\n        insecure_skip_verify: false\n        password: ''\n        token: ''\n        type: none\n        use_kiali_token: false\n        username: ''\n      cache_duration: 7\n      cache_enabled: true\n      cache_expiration: 300\n      custom_headers: {}\n      health_check_url: ''\n      is_core: true\n      query_scope: {}\n      thanos_proxy:\n        enabled: false\n        retention_period: 7d\n        scrape_interval: 30s\n      url: ''\n  grafana:\n    auth:\n      ca_file: ''\n      insecure_skip_verify: false\n      password: ''\n      token: ''\n      type: none\n      use_kiali_token: false\n      username: ''\n    dashboards:\n    - name: Istio Service Dashboard\n      variables:\n        namespace: var-namespace\n        service: var-service\n    - name: Istio Workload Dashboard\n      variables:\n        namespace: var-namespace\n        workload: var-workload\n    - name: Istio Mesh Dashboard\n    - name: Istio Control Plane Dashboard\n    - name: Istio Performance Dashboard\n    - name: Istio Wasm Extension Dashboard\n    enabled: true\n    health_check_url: ''\n    in_cluster_url: http://m001-grafana.monitoring:80\n    is_core: false\n    url: ''\n  istio:\n    component_status:\n      components:\n      - app_label: istiod\n        is_core: true\n        is_proxy: false\n        namespace: ''\n      - app_label: istio-ingressgateway\n        is_core: true\n        is_proxy: true\n        namespace: ''\n      - app_label: istio-egressgateway\n        is_core: false\n        is_proxy: true\n        namespace: ''\n      enabled: true\n    config_map_name: istio\n    envoy_admin_local_port: 15000\n    istio_identity_domain: svc.cluster.local\n    istio_injection_annotation: sidecar.istio.io/inject\n    istio_sidecar_annotation: sidecar.istio.io/status\n    istio_sidecar_injector_config_map_name: istio-sidecar-injector\n    istiod_deployment_name: istiod\n    istiod_pod_monitoring_port: 15014\n    root_namespace: istio-system\n    url_service_version: http://istiod.istio-system:15014/version\n  prometheus:\n    auth:\n      ca_file: ''\n      insecure_skip_verify: false\n      password: ''\n      token: ''\n      type: none\n      use_kiali_token: false\n      username: ''\n    cache_duration: 7\n    cache_enabled: true\n    cache_expiration: 300\n    custom_headers: {}\n    health_check_url: ''\n    is_core: true\n    query_scope: {}\n    thanos_proxy:\n      enabled: false\n      retention_period: 7d\n      scrape_interval: 30s\n    url: http://m001-kube-prometheus-stack-prometheus.monitoring:9090\n  tracing:\n    auth:\n      ca_file: ''\n      insecure_skip_verify: false\n      password: ''\n      token: ''\n      type: none\n      use_kiali_token: false\n      username: ''\n    enabled: true\n    in_cluster_url: http://tracing:16685/jaeger\n    is_core: false\n    namespace_selector: true\n    url: ''\n    use_grpc: true\n    whitelist_istio_system:\n    - jaeger-query\n    - istio-ingressgateway\nhealth_config:\n  rate: []\nidentity:\n  cert_file: ''\n  private_key_file: ''\ninstallation_tag: ''\nistio_labels:\n  app_label_name: app\n  injection_label_name: istio-injection\n  injection_label_rev: istio.io/rev\n  version_label_name: version\nistio_namespace: istio-system\nkiali_feature_flags:\n  certificates_information_indicators:\n    enabled: true\n    secrets:\n    - cacerts\n    - istio-ca-secret\n  clustering:\n    enabled: true\n  disabled_features: []\n  istio_injection_action: true\n  istio_upgrade_action: false\n  ui_defaults:\n    graph:\n      find_options:\n      - description: 'Find: slow edges (\u003e 1s)'\n        expression: rt \u003e 1000\n      - description: 'Find: unhealthy nodes'\n        expression: '! healthy'\n      - description: 'Find: unknown nodes'\n        expression: name = unknown\n      - description: 'Find: nodes with the 2 top rankings'\n        expression: rank \u003c= 2\n      hide_options:\n      - description: 'Hide: healthy nodes'\n        expression: healthy\n      - description: 'Hide: unknown nodes'\n        expression: name = unknown\n      - description: 'Hide: nodes ranked lower than the 2 top rankings'\n        expression: rank \u003e 2\n      settings:\n        font_label: 13\n        min_font_badge: 7\n        min_font_label: 10\n      traffic:\n        grpc: requests\n        http: requests\n        tcp: sent\n    metrics_inbound:\n      aggregations: []\n    metrics_outbound:\n      aggregations: []\n    metrics_per_refresh: 1m\n    namespaces: []\n    refresh_interval: 60s\n  validations:\n    ignore:\n    - KIA1201\nkubernetes_config:\n  burst: 200\n  cache_duration: 300\n  cache_enabled: true\n  cache_istio_types:\n  - AuthorizationPolicy\n  - DestinationRule\n  - EnvoyFilter\n  - Gateway\n  - PeerAuthentication\n  - RequestAuthentication\n  - ServiceEntry\n  - Sidecar\n  - VirtualService\n  - WorkloadEntry\n  - WorkloadGroup\n  cache_namespaces:\n  - .*\n  cache_token_namespace_duration: 10\n  excluded_workloads:\n  - CronJob\n  - DeploymentConfig\n  - Job\n  - ReplicationController\n  qps: 175\nlogin_token:\n  expiration_seconds: 86400\n  signing_key: secret:kiali-signing-key:key\nserver:\n  address: ''\n  audit_log: true\n  cors_allow_all: false\n  gzip_enabled: true\n  observability:\n    metrics:\n      enabled: true\n      port: 9090\n    tracing:\n      collector_url: http://jaeger-collector.istio-system:14268/api/traces\n      enabled: false\n  port: 20001\n  web_fqdn: ''\n  web_history_mode: ''\n  web_port: ''\n  web_root: /kiali\n  web_schema: ''\nversion: default\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2022-08-17T14:28:04Z","labels":{"app":"kiali","app.kubernetes.io/instance":"kiali","app.kubernetes.io/name":"kiali","app.kubernetes.io/part-of":"kiali","app.kubernetes.io/version":"v1.54.0","version":"v1.54.0"},"name":"kiali","namespace":"istio-system","ownerReferences":[{"apiVersion":"kiali.io/v1alpha1","kind":"Kiali","name":"kiali","uid":"5cf32700-690d-4ddd-8de6-d3a7d332d147"}],"resourceVersion":"3872234","uid":"84d38352-2ade-4428-add4-768b427b4358"}}
  creationTimestamp: "2022-08-17T14:28:04Z"
  labels:
    app: kiali
    app.kubernetes.io/instance: kiali
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kiali
    app.kubernetes.io/version: v1.54.0
    version: v1.54.0
  name: kiali
  namespace: istio-system
  ownerReferences:
  - apiVersion: kiali.io/v1alpha1
    kind: Kiali
    name: kiali
    uid: 5cf32700-690d-4ddd-8de6-d3a7d332d147
  resourceVersion: "3882235"
  uid: 84d38352-2ade-4428-add4-768b427b4358
