installCRDs: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    prometheusInstance: m001
    targetPort: 9402
    path: /metrics
    interval: 60s
    scrapeTimeout: 30s
    labels: 
       release: m001
    honorLabels: false
